//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quibble.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quibble.Shared.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t edit this quiz as it isn&apos;t in development..
        /// </summary>
        public static string CantEditAsQuizNotInDevelopment {
            get {
                return ResourceManager.GetString("CantEditAsQuizNotInDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t update this as the quiz is not open yet..
        /// </summary>
        public static string CantUpdateAsQuizNotOpen {
            get {
                return ResourceManager.GetString("CantUpdateAsQuizNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point values can&apos;t go over 10..
        /// </summary>
        public static string PointsTooHigh {
            get {
                return ResourceManager.GetString("PointsTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point values can&apos;t go below 0.25..
        /// </summary>
        public static string PointsTooLow {
            get {
                return ResourceManager.GetString("PointsTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update this question&apos;s state..
        /// </summary>
        public static string QuestionBadState {
            get {
                return ResourceManager.GetString("QuestionBadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A question is missing content..
        /// </summary>
        public static string QuestionMissingContent {
            get {
                return ResourceManager.GetString("QuestionMissingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question not found..
        /// </summary>
        public static string QuestionNotFound {
            get {
                return ResourceManager.GetString("QuestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent round not found..
        /// </summary>
        public static string QuestionParentRoundNotFound {
            get {
                return ResourceManager.GetString("QuestionParentRoundNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quiz is already open..
        /// </summary>
        public static string QuizAlreadyOpen {
            get {
                return ResourceManager.GetString("QuizAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quiz can&apos;t be deleted as it isn&apos;t in development..
        /// </summary>
        public static string QuizCantDeleteAsNotInDevelopment {
            get {
                return ResourceManager.GetString("QuizCantDeleteAsNotInDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t edit this quiz as you aren&apos;t it&apos;s owner..
        /// </summary>
        public static string QuizCantEditAsNotOwner {
            get {
                return ResourceManager.GetString("QuizCantEditAsNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quiz is empty..
        /// </summary>
        public static string QuizEmpty {
            get {
                return ResourceManager.GetString("QuizEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz not found..
        /// </summary>
        public static string QuizNotFound {
            get {
                return ResourceManager.GetString("QuizNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quiz is not open to join yet..
        /// </summary>
        public static string QuizNotOpen {
            get {
                return ResourceManager.GetString("QuizNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t joined this quiz yet..
        /// </summary>
        public static string QuizUserNotParticipant {
            get {
                return ResourceManager.GetString("QuizUserNotParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A round is missing a title..
        /// </summary>
        public static string RoundMissingTitle {
            get {
                return ResourceManager.GetString("RoundMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round not found..
        /// </summary>
        public static string RoundNotFound {
            get {
                return ResourceManager.GetString("RoundNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent quiz not found..
        /// </summary>
        public static string RoundParentQuizNotFound {
            get {
                return ResourceManager.GetString("RoundParentQuizNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorised to do that..
        /// </summary>
        public static string Unauthorised {
            get {
                return ResourceManager.GetString("Unauthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occured..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
