// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quibble.Data;

#nullable disable

namespace Quibble.Migrations
{
    [DbContext(typeof(QuibbleDbContext))]
    partial class QuibbleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quibble.Data.Entites.Answers.SubmittedAnswer", b =>
                {
                    b.Property<Guid>("QuestionAnswerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Points")
                        .HasColumnType("numeric");

                    b.HasKey("QuestionAnswerId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("SubmittedAnswers", (string)null);
                });

            modelBuilder.Entity("Quibble.Data.Entites.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .IsFixedLength();

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Games.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Questions.Answer.QuestionAnswer", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("QuestionId");

                    b.ToTable("QuestionAnswer");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Questions.Body.QuestionBody", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("QuestionId");

                    b.ToTable("QuestionBody");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Rounds.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Answers.SubmittedAnswer", b =>
                {
                    b.HasOne("Quibble.Data.Entites.Games.Participant", "Participant")
                        .WithMany("SubmittedAnswers")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quibble.Data.Entites.Questions.Answer.QuestionAnswer", "QuestionAnswer")
                        .WithMany("SubmittedAnswers")
                        .HasForeignKey("QuestionAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("QuestionAnswer");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Games.Game", b =>
                {
                    b.HasOne("Quibble.Data.Entites.Users.User", "Owner")
                        .WithMany("OwnedGames")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Games.Participant", b =>
                {
                    b.HasOne("Quibble.Data.Entites.Games.Game", "Game")
                        .WithMany("Participants")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quibble.Data.Entites.Users.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Questions.Answer.QuestionAnswer", b =>
                {
                    b.HasOne("Quibble.Data.Entites.Questions.Question", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("Quibble.Data.Entites.Questions.Answer.QuestionAnswer", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Questions.Body.QuestionBody", b =>
                {
                    b.HasOne("Quibble.Data.Entites.Questions.Question", "Question")
                        .WithOne("Body")
                        .HasForeignKey("Quibble.Data.Entites.Questions.Body.QuestionBody", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Questions.Question", b =>
                {
                    b.HasOne("Quibble.Data.Entites.Rounds.Round", "Round")
                        .WithMany("Questions")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Rounds.Round", b =>
                {
                    b.HasOne("Quibble.Data.Entites.Games.Game", "Game")
                        .WithMany("Rounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Games.Game", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Games.Participant", b =>
                {
                    b.Navigation("SubmittedAnswers");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Questions.Answer.QuestionAnswer", b =>
                {
                    b.Navigation("SubmittedAnswers");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Questions.Question", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();

                    b.Navigation("Body")
                        .IsRequired();
                });

            modelBuilder.Entity("Quibble.Data.Entites.Rounds.Round", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Quibble.Data.Entites.Users.User", b =>
                {
                    b.Navigation("OwnedGames");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
